title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-caymantheme: jekyll-theme-cayman
gem github-pages, group: :jekyll_plugins
